### ISSUE TITLE
Magoe is extremely slow

### ISSUE THREAD

**Issue by Popolechien** [offspot/package-requests#41] opened 2024-03-21 12:31 UTC
Trying to open an use Magoe, each page takes a few seconds to load.

**Comment by rgaudin** [comment] 2024-03-26 12:30
Thank you @Popolechien for reporting this. I did not caught it because the issue only occurs when the Pi is offline.

The issue is due to the magoe PHP code. The code is not offline-ready in that the PHP code (backend) accesses only resources when building each pages.

For instance, a call to URL `chapitre_2.php?idChapitre=3114` takes about 20 seconds to return. When the Pi is connected to the Internet, it takes about 2 seconds.

I've identified a couple scenarios:

- `curl` call to online magoe server.
- `fopen` to online resources such as videos and images
- email sending
- one of the curl call is followed by a `sleep(5)` so that's an unconditional 5s lost when this piece is triggered. 

I am closing this as this has to be fixed by magoe developers.

**Closed as completed by rgaudin** 2024-03-26 12:30 UTC
Labels: Question
